### ISSUE TITLE
[BUG]: Syntax error reported for valid syntax (unmatched unindent)

### ISSUE THREAD

**Issue by ptmcg** [wasi-master/typesplainer#2]
### Description of the bug

Using your website, I pasted in the code from the main module for littletable, and got this error message:

    Compile Error
    :1207: error: unindent does not match any outer indentation level

This *is* valid Python syntax, so there seems to be an issue with the parser.

### Steps To Reproduce

Copy the source for littletable.py (https://raw.githubusercontent.com/ptmcg/littletable/master/littletable.py).
Paste into the typesplainer website form.
Hit "typesplain".

**Comment by wasi-master** [comment]
Thanks for reporting, I just woke up and now have to go to school, I'll look it to it after coming back

**Comment by wasi-master** [comment]
I can already guess the cause of this issue and it's related to the website iteelf I am pretty sure. If possible can you please try the CLI?

**Comment by wasi-master** [comment]
It also dawned on me that type aliases aren't supported. Opened #3 to track that
